### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by vitkarpov** [LeaVerou/bubbly#2]
Lea, cool stuff!

I've found the project from the github wall, just like @matysanchez . I'd like to contribute but a little bit confused about what's your vision of the project: whom, features, what's need to be done.

Maybe it should be REAME.md with some information about that :)

Thanx!

**Comment by LeaVerou** [comment]
Frankly, this was a private repo that I made public because I needed another private repo :P 
I don't quite remember what else I wanted to do with it. I think it was buggy, but it's been so long since I worked on it that I don't remember in what way.
What did you have in mind?

**Comment by vitkarpov** [comment]
Hah! Considering code it's looks like idea proof or smth like that, that's clear. But I saw the demo page and it looks like gradient generator or whatever generator web service. I thought you wanna make some bubbles generator :+1:

**Comment by LeaVerou** [comment]
> I thought you wanna make some bubbles generator :+1:

Yup, that’s correct.
